module.exports = {
  apps: [
    {
      name: 'streammonitor',
      script: '/root/StreamCheck/StreamMonitor/main.py',
      interpreter: '/root/StreamCheck/venv/bin/python3',
      cwd: '/root/StreamCheck/StreamMonitor',
      args: '--record-stats --verbose',
      restart_delay: 30000,
      max_restarts: 20,
      error_file: '/root/StreamCheck/logs/streammonitor-err.log',
      out_file: '/root/StreamCheck/logs/streammonitor-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'streamweb',
      script: '/root/StreamCheck/StreamMonitor/web_server.py',
      interpreter: '/root/StreamCheck/venv/bin/python3',
      cwd: '/root/StreamCheck/StreamMonitor',
      restart_delay: 5000,
      max_restarts: 10,
      error_file: '/root/StreamCheck/logs/streamweb-err.log',
      out_file: '/root/StreamCheck/logs/streamweb-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      env: { NODE_ENV: 'production', WEB_PORT: '5000', WEB_HOST: '0.0.0.0' },
    },
    {
      name: 'bilibili-checker',
      script: '/root/StreamCheck/check/checker.py',
      interpreter: '/root/StreamCheck/venv/bin/python3',
      cwd: '/root/StreamCheck/check',
      restart_delay: 30000,
      max_restarts: 20,
      error_file: '/root/StreamCheck/logs/bilibili-checker-err.log',
      out_file: '/root/StreamCheck/logs/bilibili-checker-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'cookie-refresher',
      script: '/root/StreamCheck/StreamMonitor/cookie_refresher.py',
      interpreter: '/root/StreamCheck/venv/bin/python3',
      cwd: '/root/StreamCheck/StreamMonitor',
      args: '21600',
      restart_delay: 60000,
      max_restarts: 5,
      error_file: '/root/StreamCheck/logs/cookie-refresher-err.log',
      out_file: '/root/StreamCheck/logs/cookie-refresher-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
    },
  ]
};
