module.exports = {
  apps: [
    {
      name: 'streammonitor',
      script: '/root/StreamCheck/StreamMonitor/main.py',
      interpreter: '/root/StreamCheck/venv/bin/python3',
      cwd: '/root/StreamCheck/StreamMonitor',
      args: '--record-stats --verbose',
      restart_delay: 30000,
      max_restarts: 100,
      error_file: '/root/StreamCheck/logs/streammonitor-err.log',
      out_file: '/root/StreamCheck/logs/streammonitor-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'streamweb',
      script: '/root/StreamCheck/StreamMonitor/web_server.py',
      interpreter: '/root/StreamCheck/venv/bin/python3',
      cwd: '/root/StreamCheck/StreamMonitor',
      restart_delay: 5000,
      max_restarts: 100,
      error_file: '/root/StreamCheck/logs/streamweb-err.log',
      out_file: '/root/StreamCheck/logs/streamweb-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      env: { NODE_ENV: 'production', WEB_PORT: '5000', WEB_HOST: '0.0.0.0' },
    },
    {
      name: 'bilibili-checker',
      script: '/root/StreamCheck/check/checker.py',
      interpreter: '/root/StreamCheck/venv/bin/python3',
      cwd: '/root/StreamCheck/check',
      restart_delay: 30000,
      max_restarts: 100,
      error_file: '/root/StreamCheck/logs/bilibili-checker-err.log',
      out_file: '/root/StreamCheck/logs/bilibili-checker-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'cookie-refresher',
      script: '/root/StreamCheck/StreamMonitor/cookie_refresher.py',
      interpreter: '/root/StreamCheck/venv/bin/python3',
      cwd: '/root/StreamCheck/StreamMonitor',
      args: '21600',
      restart_delay: 60000,
      max_restarts: 100,
      error_file: '/root/StreamCheck/logs/cookie-refresher-err.log',
      out_file: '/root/StreamCheck/logs/cookie-refresher-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
    },
    {
      name: 'weibo-cookie-refresher',
      script: '/root/StreamCheck/StreamMonitor/weibo_cookie_refresher.py',
      interpreter: '/root/StreamCheck/venv/bin/python3',
      cwd: '/root/StreamCheck/StreamMonitor',
      args: '43200',
      restart_delay: 60000,
      max_restarts: 100,
      error_file: '/root/StreamCheck/logs/weibo-cookie-refresher-err.log',
      out_file: '/root/StreamCheck/logs/weibo-cookie-refresher-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
    },
    {
      name: 'bilibili-cookie-refresher',
      script: '/root/StreamCheck/StreamMonitor/bilibili_cookie_refresher.py',
      interpreter: '/root/StreamCheck/venv/bin/python3',
      cwd: '/root/StreamCheck/StreamMonitor',
      args: '86400',
      restart_delay: 60000,
      max_restarts: 100,
      error_file: '/root/StreamCheck/logs/bilibili-cookie-refresher-err.log',
      out_file: '/root/StreamCheck/logs/bilibili-cookie-refresher-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
    },
    {
      name: 'weiboclient',
      script: '/root/weiboclient/server.js',
      cwd: '/root/weiboclient',
      restart_delay: 10000,
      max_restarts: 100,
      error_file: '/root/StreamCheck/logs/weiboclient-err.log',
      out_file: '/root/StreamCheck/logs/weiboclient-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      env: { NODE_ENV: 'production', PORT: '3000' },
    },
  ]
};
